name: BPB Worker Ultimate Fix

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: ""

      - name: Install verified deps
        run: |
          npm install -g javascript-obfuscator@4.0.2
          npm install -g wrangler@4.7.0  # 使用验证可用版本

      - name: Process source
        run: |
          curl -sSf -o origin.js \
            "https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js"
          
          # 全量WHOER伪装
          sed -i '
            s/window\./globalThis./g;
            s/document\./{};/g;
            s/navigator\.userAgent/"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36"/g;
            s/new Date()/new Date(Date.now() + 28800000)/g;
            s/\.headers\.get("Accept-Language")/"en-US,en;q=0.9"/g;
            s/\.cf\.country/"US"/g;
            s/\.cf\.colo/"IAD"/g;
            s/\.remoteAddress/"8.8.8.8"/g;
          ' origin.js

      - name: Obfuscate
        run: |
          javascript-obfuscator origin.js \
            --output _worker.js \
            --compact true \
            --identifier-names-generator hexadecimal \
            --rename-globals false \
            --reserved-names "fetch,Response,Request,Headers,US,IAD"

      - name: Deploy to CF
        run: |
          wrangler deploy _worker.js \
            --name hz567 \
            --compatibility-date $(date +'%Y-%m-%d')
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: a6cb67cd0093862666e9c34e3e2e3a61  # 直接嵌入您的账户ID
