name: BPB Worker 100% Camouflage

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          npm install -g javascript-obfuscator@4.0.2
          npm install -g wrangler@4.12.0  # 验证可用的最新稳定版

      - name: Process Code
        run: |
          curl -sSf -o raw.js https://example.com/your-worker-code
          
          # WHOER 100%伪装核心
          sed -i '
            s/window\./globalThis.location=/g;
            s/document\./void 0;/g;
            s/navigator\.userAgent/"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36"/g;
            s/new Date()/new Date(Date.now() + 28800000)/g;
            s/\.headers\.get("Accept-Language")/"en-US,en;q=0.9"/g;
            s/\.cf\.country/"US"/g;
            s/\.cf\.colo/"IAD"/g;
            s/\.remoteAddress/"8.8.8.8"/g;
          ' raw.js

          # 生成合规Worker模块
          echo "export default {" > _worker.js
          echo "  async fetch(request) {" >> _worker.js
          cat raw.js >> _worker.js
          echo "}}" >> _worker.js

      - name: Deploy with Security
        run: |
          wrangler deploy _worker.js \
            --name hz567 \
            --compatibility-date 2024-03-01 \
            --account-id a6cb67cd0093862666e9c34e3e2e3a61
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
