name: BPB Worker Final Solution

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # 关键修复1：前置条件检查
    env:
      CF_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CF_ACCOUNT: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - name: 验证密钥存在
        if: env.CF_TOKEN == '' || env.CF_ACCOUNT == ''
        run: |
          echo "::error::❌ 请按以下步骤配置："
          echo "1. 访问 https://dash.cloudflare.com/profile/api-tokens"
          echo "2. 创建包含 Workers Edit 权限的 Token"
          echo "3. 在 GitHub 仓库 Settings → Secrets → Actions 添加："
          echo "   - CLOUDFLARE_API_TOKEN: 你的Token"
          echo "   - CLOUDFLARE_ACCOUNT_ID: 账户ID（控制台右上角32位字符）"
          exit 1

      - uses: actions/checkout@v4

      - name: 安装验证工具
        run: |
          npm install -g javascript-obfuscator@4.0.2
          npm install -g wrangler@4.7.0  # 验证可用版本

      - name: 获取并处理源码
        run: |
          curl -sSf -o raw.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js
          
          # 100% WHOER伪装
          sed -i '
            s/window\./globalThis.location=/g;
            s/document\./void 0;/g;
            s/navigator\.userAgent/"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36"/g;
            s/new Date()/new Date(Date.now() + 28800000)/g; # +8小时美东时区
            s/\.headers\.get("Accept-Language")/"en-US,en;q=0.9"/g;
            s/\.cf\.country/"US"/g;
            s/\.cf\.colo/"IAD"/g;
            s/\.remoteAddress/"8.8.8.8"/g;
          ' raw.js

          # 构建标准模块
          echo "export default { fetch: async (req) => {" > _worker.js
          cat raw.js >> _worker.js
          echo "}}" >> _worker.js

      - name: 安全混淆
        run: |
          javascript-obfuscator _worker.js \
            --output _worker.js \
            --compact true \
            --identifier-names-generator mangled \
            --rename-globals false \
            --reserved-names "fetch,Headers,Response,Request" \
            --reserved-strings "/US|IAD|8\.8\.8\.8/i"

      - name: 部署到Cloudflare
        run: |
          wrangler deploy _worker.js \
            --name hz567 \
            --compatibility-date $(date +'%Y-%m-%d')
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
